name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to cPanel
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        npm install

    - name: list pre build
      run: |
        tree

    - name: Build
      run: |
        CI=false npm run build  # If applicable, run the build command
    
    - name: list post build
      run: |
        tree
